services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: galactic_admin
      POSTGRES_PASSWORD: force_password
      POSTGRES_DB: smart_booking_db
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app           # Changed to match WORKDIR /app
      - /app/node_modules        # Protects container modules from Windows
    environment:
      - DATABASE_URL=postgres://galactic_admin:force_password@db:5432/smart_booking_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend